# MegaLinter configuration file
# See https://megalinter.io/latest/configuration/

KOTLIN_KTLINT_ARGUMENTS: --baseline=.github/linters/ktlint-baseline.xml

#TODO PYTHON_ISORT_ARGUMENTS: "--profile black"

GITHUB_STATUS_REPORTER: true

# Does nothing but reminds you to use the version that you're using...
SECURITY_SUGGESTIONS: false
